export { calcHeroPositionAfterMoving } from './calcHeroPositionAfterMoving'
export { calcHeroSizeAfterMoving } from './calcHeroSizeAfterMoving'
export { calcHeroStateAfterMoving } from './calcHeroStateAfterMoving'
export { calcStateAfterActionApplied } from './calcStateAfterActionApplied'
export { calcStateAfterMoving } from './calcStateAfterMoving'
export { checkForHeroBlockOutOfMap } from './checkForHeroBlockOutOfMap'
export { getGameBoardAction } from './getGameBoardAction'
