export { Button } from './Button'
export { Content } from './Content'
export { Footer } from './Footer'
export { GameBoard } from './GameBoard'
export { Hero } from './Hero'
export { VictoryModal } from './VictoryModal'
export { Nav } from './Nav'
export { GameStatusTitle } from './GameStatusTitle'
